### ISSUE TITLE
TLSAttackerConnector problem

### ISSUE THREAD

**Issue by mahabhu** [jderuiter/statelearner#11] opened 2024-06-19 11:28 UTC
after successfully installing the package, running the command "java -jar target/TLSAttackerConnector2.0.jar <any parameter>" shows the following error message:

Exception in thread "main" java.lang.ExceptionInInitializerError
        at nl.cypherpunk.tlsattackerconnector.TLSAttackerConnector.initialise(TLSAttackerConnector.java:112)
        at nl.cypherpunk.tlsattackerconnector.TLSAttackerConnector.main(TLSAttackerConnector.java:447)
Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.UnmarshalException: Unable to create an instance of de.rub.nds.tlsattacker.core.config.Config
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:211)
        at de.rub.nds.tlsattacker.core.config.ConfigIO.read(ConfigIO.java:61)
        at de.rub.nds.tlsattacker.core.config.Config.createConfig(Config.java:100)
        at de.rub.nds.tlsattacker.core.config.Config.<clinit>(Config.java:92)
        ... 2 more

and many more

what might be the possible reason for this, and how to fix this.

**Comment by jderuiter** [comment] 2024-06-20 09:14
duplicate of https://github.com/jderuiter/TLSAttackerConnector/issues/1

**Closed as not planned by jderuiter** 2024-06-20 09:14 UTC
